# Kolmogorov-Smirnoff test

In [1]:
from scipy.stats import ks_2samp

In [2]:
import pandas as pd

### Low train set

In [3]:
df_low_low = pd.read_excel('df_low_low.xlsx')
df_low_low

    accuracy        f1    recall  precision
0   0.750000  0.740516  0.777070   0.707246
1   0.878655  0.873282  0.910828   0.838710
2   0.944444  0.942771  0.996815   0.894286
3   0.988304  0.987342  0.993631   0.981132
4   0.997076  0.996825  1.000000   0.993671
5   0.985380  0.984227  0.993631   0.975000
6   0.994152  0.993610  0.990446   0.996795
7   0.994152  0.993610  0.990446   0.996795
8   0.997076  0.996805  0.993631   1.000000
9   0.995614  0.995246  1.000000   0.990536
10  0.998538  0.998410  1.000000   0.996825
11  0.994152  0.993651  0.996815   0.990506
12  0.997076  0.996815  0.996815   0.996815
13  0.995614  0.995231  0.996815   0.993651
14  0.994143  0.993610  0.990446   0.996795
15  0.997072  0.996795  0.993610   1.000000
16  0.995608  0.995200  0.993610   0.996795
17  1.000000  1.000000  1.000000   1.000000
18  1.000000  1.000000  1.000000   1.000000
19  0.997072  0.996795  0.993610   1.000000
20  0.974706  0.973537  0.980411   0.967278

In [4]:
df_low_med = pd.read_excel('df_low_med.xlsx')
df_low_med

    accuracy        f1    recall  precision
0   0.742690  0.730887  0.705015   0.758730
1   0.739766  0.731118  0.705539   0.758621
2   0.736842  0.731343  0.688202   0.780255
3   0.758772  0.754098  0.706704   0.808307
4   0.754386  0.749254  0.709040   0.794304
5   0.763158  0.752294  0.740964   0.763975
6   0.763158  0.756024  0.717143   0.799363
7   0.735380  0.721966  0.701493   0.743671
8   0.742690  0.733333  0.699422   0.770701
9   0.750000  0.742857  0.707736   0.781646
10  0.713450  0.710914  0.665746   0.762658
11  0.735380  0.726172  0.691643   0.764331
12  0.752924  0.739599  0.712166   0.769231
13  0.761696  0.754887  0.713068   0.801917
14  0.764275  0.751926  0.730539   0.774603
15  0.762811  0.750000  0.725373   0.776358
16  0.754026  0.739938  0.711310   0.770968
17  0.767204  0.760902  0.714689   0.813505
18  0.749634  0.734884  0.716012   0.754777
19  0.748170  0.732919  0.708709   0.758842
20  0.749821  0.740266  0.708526   0.775338

In [5]:
df_low_high = pd.read_excel('df_low_high.xlsx')
df_low_high

    accuracy        f1    recall  precision
0   0.728070  0.704762  0.702532   0.707006
1   0.717836  0.696063  0.686335   0.706070
2   0.760234  0.746130  0.728097   0.765079
3   0.782164  0.766823  0.751534   0.782748
4   0.751462  0.736842  0.719033   0.755556
5   0.741228  0.724728  0.703927   0.746795
6   0.745614  0.732308  0.710448   0.755556
7   0.744152  0.726989  0.710366   0.744409
8   0.729532  0.714946  0.692537   0.738854
9   0.745614  0.731481  0.713855   0.750000
10  0.757310  0.746177  0.717647   0.777070
11  0.739766  0.721875  0.706422   0.738019
12  0.755848  0.732800  0.741100   0.724684
13  0.767544  0.751174  0.738462   0.764331
14  0.724744  0.696774  0.708197   0.685714
15  0.743777  0.722662  0.716981   0.728435
16  0.764275  0.743222  0.735016   0.751613
17  0.745242  0.728972  0.711246   0.747604
18  0.756955  0.742236  0.719880   0.766026
19  0.723280  0.696629  0.702265   0.691083
20  0.746232  0.728180  0.715794   0.741333

In [6]:
df_low_mix = pd.read_excel('df_low_mix.xlsx')
df_low_mix

    accuracy        f1    recall  precision
0   0.770468  0.755832  0.736364   0.776358
1   0.785088  0.772798  0.750751   0.796178
2   0.774854  0.761610  0.738739   0.785942
3   0.821637  0.809969  0.792683   0.828025
4   0.788012  0.777948  0.749263   0.808917
5   0.795322  0.781931  0.765244   0.799363
6   0.808480  0.797527  0.772455   0.824281
7   0.796784  0.779014  0.777778   0.780255
8   0.790936  0.779661  0.755224   0.805732
9   0.789474  0.780488  0.748538   0.815287
10  0.823099  0.811232  0.800000   0.822785
11  0.792398  0.780186  0.756757   0.805112
12  0.821637  0.809375  0.787234   0.832797
13  0.820175  0.810478  0.785075   0.837580
14  0.764275  0.748830  0.736196   0.761905
15  0.790630  0.768233  0.766990   0.769481
16  0.792094  0.775316  0.763240   0.787781
17  0.802343  0.790698  0.768072   0.814696
18  0.821376  0.805732  0.805732   0.805732
19  0.787701  0.768740  0.757862   0.779935
20  0.796839  0.783280  0.765710   0.801907

### Medium train set

In [7]:
df_med_low = pd.read_excel('df_med_low.xlsx')
df_med_low

    accuracy        f1    recall  precision
0   0.868421  0.865672  0.917722   0.819209
1   0.785088  0.778281  0.837662   0.726761
2   0.732456  0.731278  0.787975   0.682192
3   0.750000  0.758133  0.795252   0.724324
4   0.795322  0.789157  0.845161   0.740113
5   0.735380  0.720247  0.774086   0.673410
6   0.776316  0.775330  0.783383   0.767442
7   0.790936  0.783661  0.817035   0.752907
8   0.733918  0.727545  0.747692   0.708455
9   0.750000  0.738931  0.778135   0.703488
10  0.719298  0.700935  0.765306   0.646552
11  0.767544  0.763744  0.793210   0.736390
12  0.757310  0.739812  0.800000   0.688047
13  0.751462  0.743976  0.760000   0.728614
14  0.730600  0.711599  0.774744   0.657971
15  0.733529  0.720859  0.767974   0.679191
16  0.729136  0.726736  0.736527   0.717201
17  0.749634  0.731554  0.787162   0.683284
18  0.717423  0.708899  0.741325   0.679191
19  0.765739  0.757576  0.798722   0.720461
20  0.756976  0.748696  0.790454   0.711760

In [8]:
df_med_med = pd.read_excel('df_med_med.xlsx')
df_med_med

    accuracy        f1    recall  precision
0   0.989766  0.989899  0.994203   0.985632
1   0.997076  0.997101  0.997101   0.997101
2   0.922515  0.928475  0.997101   0.868687
3   0.864035  0.880616  0.997093   0.788506
4   0.989766  0.989811  0.988372   0.991254
5   0.964912  0.963964  0.933140   0.996894
6   0.980994  0.981077  0.979651   0.982507
7   0.998538  0.998549  1.000000   0.997101
8   0.994152  0.994220  1.000000   0.988506
9   0.687135  0.762222  0.997093   0.616906
10  0.928363  0.932969  0.991279   0.881137
11  0.972222  0.972896  0.991279   0.955182
12  0.967836  0.967164  0.941860   0.993865
13  0.985380  0.985423  0.982558   0.988304
14  0.972182  0.972018  0.959302   0.985075
15  0.980966  0.981349  0.994186   0.968839
16  0.991215  0.991304  0.994186   0.988439
17  0.982430  0.982609  0.985465   0.979769
18  0.966325  0.966325  0.959302   0.973451
19  0.983895  0.984127  0.991279   0.977077
20  0.955985  0.961106  0.983723   0.945212

In [9]:
df_med_high = pd.read_excel('df_med_high.xlsx')
df_med_high

    accuracy        f1    recall  precision
0   0.790936  0.787519  0.820433   0.757143
1   0.776316  0.773333  0.815625   0.735211
2   0.748538  0.737003  0.779935   0.698551
3   0.769006  0.763473  0.806962   0.724432
4   0.777778  0.772455  0.801242   0.745665
5   0.814327  0.809023  0.851266   0.770774
6   0.773392  0.769001  0.796296   0.743516
7   0.802632  0.791988  0.769461   0.815873
8   0.789474  0.787611  0.801802   0.773913
9   0.777778  0.782857  0.813056   0.754821
10  0.777778  0.770393  0.812102   0.732759
11  0.752924  0.756133  0.850649   0.680519
12  0.766082  0.761905  0.766467   0.757396
13  0.804094  0.800595  0.820122   0.781977
14  0.775988  0.775330  0.807339   0.745763
15  0.765739  0.751553  0.798680   0.709677
16  0.793558  0.796537  0.793103   0.800000
17  0.777452  0.773810  0.795107   0.753623
18  0.771596  0.770588  0.777448   0.763848
19  0.792094  0.793003  0.804734   0.781609
20  0.779874  0.776205  0.804092   0.751354

In [10]:
df_med_mix = pd.read_excel('df_med_mix.xlsx')
df_med_mix

    accuracy        f1    recall  precision
0   0.828947  0.824060  0.858934   0.791908
1   0.830409  0.827893  0.850610   0.806358
2   0.802632  0.798808  0.819572   0.779070
3   0.799708  0.797037  0.805389   0.788856
4   0.485380  0.652860  1.000000   0.484627
5   0.826023  0.821589  0.864353   0.782857
6   0.809942  0.811047  0.835329   0.788136
7   0.846491  0.846715  0.850440   0.843023
8   0.804094  0.798193  0.812883   0.784024
9   0.807018  0.810888  0.815562   0.806268
10  0.807018  0.796296  0.851485   0.747826
11  0.823099  0.821797  0.850610   0.794872
12  0.823099  0.818045  0.852665   0.786127
13  0.814327  0.813510  0.824405   0.802899
14  0.796486  0.788432  0.824841   0.755102
15  0.796486  0.787786  0.829582   0.750000
16  0.825769  0.830243  0.829060   0.831429
17  0.831625  0.828614  0.847561   0.810496
18  0.812592  0.810089  0.822289   0.798246
19  0.836018  0.834320  0.846847   0.822157
20  0.800358  0.805911  0.844621   0.777714

## High train data

In [11]:
df_high_low = pd.read_excel('df_high_low.xlsx')
df_high_low

    accuracy        f1    recall  precision
0   0.773392  0.769688  0.814465   0.729577
1   0.779240  0.778917  0.831250   0.732782
2   0.802632  0.789392  0.834983   0.748521
3   0.812865  0.800623  0.815873   0.785933
4   0.808480  0.799387  0.805556   0.793313
5   0.785088  0.776256  0.789474   0.763473
6   0.764620  0.752688  0.758514   0.746951
7   0.817251  0.805599  0.827476   0.784848
8   0.795322  0.779874  0.810458   0.751515
9   0.807018  0.797546  0.817610   0.778443
10  0.811404  0.794913  0.830565   0.762195
11  0.783626  0.771605  0.778816   0.764526
12  0.799708  0.780800  0.827119   0.739394
13  0.789474  0.779141  0.781538   0.776758
14  0.809663  0.799383  0.811912   0.787234
15  0.797950  0.785714  0.800633   0.771341
16  0.808199  0.794349  0.821429   0.768997
17  0.793558  0.772213  0.818493   0.730887
18  0.786237  0.778788  0.774096   0.783537
19  0.765739  0.746032  0.775578   0.718654
20  0.794573  0.782645  0.806292   0.760944

In [12]:
df_high_med = pd.read_excel('df_high_med.xlsx')
df_high_med

    accuracy        f1    recall  precision
0   0.799708  0.801161  0.793103   0.809384
1   0.814327  0.814056  0.794286   0.834835
2   0.798246  0.786378  0.751479   0.824675
3   0.785088  0.780269  0.711172   0.864238
4   0.817251  0.813711  0.793605   0.834862
5   0.799708  0.800000  0.787356   0.813056
6   0.809942  0.808260  0.776204   0.843077
7   0.745614  0.728972  0.670487   0.798635
8   0.788012  0.785185  0.768116   0.803030
9   0.782164  0.781845  0.758523   0.806647
10  0.769006  0.762763  0.736232   0.791277
11  0.790936  0.777605  0.746269   0.811688
12  0.782164  0.783115  0.751397   0.817629
13  0.788012  0.778626  0.779817   0.777439
14  0.752562  0.741985  0.734139   0.750000
15  0.773060  0.771723  0.738028   0.808642
16  0.754026  0.750742  0.722857   0.780864
17  0.802343  0.793262  0.784848   0.801858
18  0.836018  0.833333  0.858896   0.809249
19  0.800878  0.793939  0.789157   0.798780
20  0.789453  0.784346  0.762298   0.808993

In [13]:
df_high_high = pd.read_excel('df_high_high.xlsx')
df_high_high

    accuracy        f1    recall  precision
0   0.976608  0.975460  0.978462   0.972477
1   0.535088  0.042169  0.021538   1.000000
2   0.961988  0.960123  0.963077   0.957187
3   0.992690  0.992320  0.993846   0.990798
4   0.918129  0.906667  0.836923   0.989091
5   0.982456  0.981481  0.978462   0.984520
6   0.988304  0.987616  0.981538   0.993769
7   0.994152  0.993827  0.990769   0.996904
8   0.991228  0.990769  0.990769   0.990769
9   0.989766  0.989214  0.987692   0.990741
10  0.994152  0.993827  0.990769   0.996904
11  0.476608  0.642715  0.990769   0.475628
12  0.995614  0.995392  0.996923   0.993865
13  0.998538  0.998459  0.996923   1.000000
14  0.969253  0.966614  0.935385   1.000000
15  0.973646  0.971963  0.960000   0.984227
16  0.982430  0.981366  0.972308   0.990596
17  0.985359  0.984472  0.975385   0.993730
18  0.985359  0.984424  0.975309   0.993711
19  0.980966  0.979782  0.972222   0.987461
20  0.933617  0.915933  0.924453   0.964119

In [14]:
df_high_mix = pd.read_excel('df_high_mix.xlsx')
df_high_mix

    accuracy        f1    recall  precision
0   0.818713  0.815476  0.817910   0.813056
1   0.820175  0.809302  0.825949   0.793313
2   0.837719  0.832073  0.820896   0.843558
3   0.836257  0.833333  0.802292   0.866873
4   0.846491  0.836703  0.822630   0.851266
5   0.839181  0.830247  0.832817   0.827692
6   0.814327  0.812960  0.838906   0.788571
7   0.782164  0.774584  0.764179   0.785276
8   0.761696  0.766810  0.834891   0.708995
9   0.808480  0.799387  0.805556   0.793313
10  0.500000  0.000000  0.000000   0.000000
11  0.799708  0.793363  0.789790   0.796970
12  0.802632  0.802343  0.798834   0.805882
13  0.836257  0.834320  0.834320   0.834320
14  0.786237  0.773994  0.769231   0.778816
15  0.540264  0.065476  0.034591   0.611111
16  0.833089  0.820755  0.828571   0.813084
17  0.831625  0.819466  0.839228   0.800613
18  0.830161  0.820433  0.843949   0.798193
19  0.812592  0.791531  0.745399   0.843750
20  0.786888  0.731628  0.732497   0.757733

## KS for destributions of performance values

### Get Macro-Avg. f1-scores of all Train/test combinations (n= 12) and all runs (n= 20)

In [15]:
#Store all values from data frames in a list, row 20 (aggregated value) is excluded
dflist = [list(df_low_low["f1"][:20]),
          list(df_low_med["f1"][:20]),
          list(df_low_high["f1"][:20]),
          list(df_low_mix["f1"][:20]),
          
          list(df_med_low["f1"][:20]),
          list(df_med_med["f1"][:20]),
          list(df_med_high["f1"][:20]),
          list(df_med_mix["f1"][:20]),
         
          list(df_high_low["f1"][:20]),
          list(df_high_med["f1"][:20]),
          list(df_high_high["f1"][:20]),
          list(df_high_mix["f1"][:20]),
         
         ]

### Get all combinations of two for the 2 sample KS test

In [16]:
#Assign labels to the data frames for permutation overview

dflist_label = ["df_low_low", "df_low_med", "df_low_high", "df_low_mix",
                
                "df_med_low", "df_med_med", "df_med_high", "df_med_mix",
                
                "df_high_low", "df_high_med", "df_high_high", "df_high_mix",
         
         ]

In [17]:
#Permutation: Get all combination of test combinations for 2-sample KS-test from the list of data frames
res = [(a, b) for idx, a in enumerate(dflist) for b in dflist[idx + 1:]]

In [18]:
len(res)

66

In [19]:
res[0] #First combination

([0.7405159332321699,
  0.8732824427480916,
  0.9427710843373494,
  0.9873417721518988,
  0.9968253968253968,
  0.9842271293375395,
  0.9936102236421726,
  0.9936102236421726,
  0.9968051118210862,
  0.9952456418383517,
  0.9984101748807631,
  0.9936507936507937,
  0.9968152866242038,
  0.9952305246422894,
  0.9936102236421726,
  0.9967948717948718,
  0.9952,
  1.0,
  1.0,
  0.9967948717948718],
 [0.7308868501529052,
  0.7311178247734138,
  0.7313432835820896,
  0.7540983606557377,
  0.7492537313432835,
  0.7522935779816513,
  0.7560240963855422,
  0.7219662058371736,
  0.7333333333333335,
  0.742857142857143,
  0.7109144542772862,
  0.7261724659606658,
  0.7395993836671803,
  0.7548872180451127,
  0.7519260400616332,
  0.75,
  0.7399380804953561,
  0.7609022556390976,
  0.7348837209302326,
  0.7329192546583851])

In [20]:
res[0][0] # Destribution in first data frame in first combination

[0.7405159332321699,
 0.8732824427480916,
 0.9427710843373494,
 0.9873417721518988,
 0.9968253968253968,
 0.9842271293375395,
 0.9936102236421726,
 0.9936102236421726,
 0.9968051118210862,
 0.9952456418383517,
 0.9984101748807631,
 0.9936507936507937,
 0.9968152866242038,
 0.9952305246422894,
 0.9936102236421726,
 0.9967948717948718,
 0.9952,
 1.0,
 1.0,
 0.9967948717948718]

In [21]:
#Permutation: Get all combination of test combinations for 2-sample KS-test from the labels
res_label = [(a, b) for idx, a in enumerate(dflist_label) for b in dflist_label[idx + 1:]]
for i in res_label:
    print(str(i))

('df_low_low', 'df_low_med')
('df_low_low', 'df_low_high')
('df_low_low', 'df_low_mix')
('df_low_low', 'df_med_low')
('df_low_low', 'df_med_med')
('df_low_low', 'df_med_high')
('df_low_low', 'df_med_mix')
('df_low_low', 'df_high_low')
('df_low_low', 'df_high_med')
('df_low_low', 'df_high_high')
('df_low_low', 'df_high_mix')
('df_low_med', 'df_low_high')
('df_low_med', 'df_low_mix')
('df_low_med', 'df_med_low')
('df_low_med', 'df_med_med')
('df_low_med', 'df_med_high')
('df_low_med', 'df_med_mix')
('df_low_med', 'df_high_low')
('df_low_med', 'df_high_med')
('df_low_med', 'df_high_high')
('df_low_med', 'df_high_mix')
('df_low_high', 'df_low_mix')
('df_low_high', 'df_med_low')
('df_low_high', 'df_med_med')
('df_low_high', 'df_med_high')
('df_low_high', 'df_med_mix')
('df_low_high', 'df_high_low')
('df_low_high', 'df_high_med')
('df_low_high', 'df_high_high')
('df_low_high', 'df_high_mix')
('df_low_mix', 'df_med_low')
('df_low_mix', 'df_med_med')
('df_low_mix', 'df_med_high')
('df_low_mix', 'df_med_mix')
('df_low_mix', 'df_high_low')
('df_low_mix', 'df_high_med')
('df_low_mix', 'df_high_high')
('df_low_mix', 'df_high_mix')
('df_med_low', 'df_med_med')
('df_med_low', 'df_med_high')
('df_med_low', 'df_med_mix')
('df_med_low', 'df_high_low')
('df_med_low', 'df_high_med')
('df_med_low', 'df_high_high')
('df_med_low', 'df_high_mix')
('df_med_med', 'df_med_high')
('df_med_med', 'df_med_mix')
('df_med_med', 'df_high_low')
('df_med_med', 'df_high_med')
('df_med_med', 'df_high_high')
('df_med_med', 'df_high_mix')
('df_med_high', 'df_med_mix')
('df_med_high', 'df_high_low')
('df_med_high', 'df_high_med')
('df_med_high', 'df_high_high')
('df_med_high', 'df_high_mix')
('df_med_mix', 'df_high_low')
('df_med_mix', 'df_high_med')
('df_med_mix', 'df_high_high')
('df_med_mix', 'df_high_mix')
('df_high_low', 'df_high_med')
('df_high_low', 'df_high_high')
('df_high_low', 'df_high_mix')
('df_high_med', 'df_high_high')
('df_high_med', 'df_high_mix')
('df_high_high', 'df_high_mix')

In [22]:
len(res_label)

66

### Apply 2 sample KS test

#### test

In [23]:
res_label[0] #First combination

('df_low_low', 'df_low_med')

In [24]:
res_label[0][0] # Label of first data frame in first combination

'df_low_low'

In [25]:
ks_2samp(res[0][0],res[0][1]) #KS test for first combination

KstestResult(statistic=0.95, pvalue=5.803555641539872e-10, statistic_location=0.7609022556390976, statistic_sign=-1)

In [26]:
result = ks_2samp(res[0][0],res[0][1]) #KS test for first combination
print("pvalue= ", (result[1]))
print("pvalue rounded= ", round(result[1],2))

pvalue=  5.803555641539872e-10
pvalue rounded=  0.0

#### Loop to apply 2 sample KS test for all combinations

In [27]:
#Prints only non-significant deviations between 2 destributions

for label,i in zip(res_label, res):

   
    for e in i:
        list1 = i[0]
        list2 = i[1]
        ks = ks_2samp(list1,list2)



    if (ks[1]) <= 0.5:
        #print(label)
        #print("ks_value", ks[0])
        #print("p_value", round(ks[1],2))
        pass
    else:
        print("No difference: ", label)
        print("p_value", round(ks[1],2))

No difference:  ('df_low_mix', 'df_med_high')
p_value 0.57
No difference:  ('df_low_mix', 'df_high_low')
p_value 0.57
No difference:  ('df_low_mix', 'df_high_med')
p_value 0.83
No difference:  ('df_med_med', 'df_high_high')
p_value 0.98
No difference:  ('df_med_mix', 'df_high_mix')
p_value 0.83
No difference:  ('df_high_low', 'df_high_med')
p_value 0.83

In [28]:
#Saves values of significant results in list
def ks_all(res, res_label):
    
    liste_labels = []
    liste_p = []
    liste_ks = []


    
    for label,i in zip(res_label, res):

   
        for e in i:
            list1 = i[0]
            list2 = i[1]
            ks = ks_2samp(list1,list2)


        if (ks[1]) <= 0.5:

            liste_labels.append(label)
            liste_ks.append(ks[0])
            liste_p.append(round(ks[1],2))
        else:
            pass


        
    return liste_labels, liste_p, liste_ks

In [29]:
a,b,c = ks_all(res, res_label)

In [30]:
df_ks_results = pd.DataFrame(
    {'combination': a,
     'p_value': b,
     'ks': c
    })

In [31]:
df_ks_results

                    combination  p_value    ks
0      (df_low_low, df_low_med)     0.00  0.95
1     (df_low_low, df_low_high)     0.00  0.95
2      (df_low_low, df_low_mix)     0.00  0.95
3      (df_low_low, df_med_low)     0.00  0.95
4      (df_low_low, df_med_med)     0.00  0.60
5     (df_low_low, df_med_high)     0.00  0.95
6      (df_low_low, df_med_mix)     0.00  0.95
7     (df_low_low, df_high_low)     0.00  0.95
8     (df_low_low, df_high_med)     0.00  0.95
9    (df_low_low, df_high_high)     0.00  0.55
10    (df_low_low, df_high_mix)     0.00  0.95
11    (df_low_med, df_low_high)     0.17  0.35
12     (df_low_med, df_low_mix)     0.00  0.90
13     (df_low_med, df_med_low)     0.17  0.35
14     (df_low_med, df_med_med)     0.00  1.00
15    (df_low_med, df_med_high)     0.00  0.85
16     (df_low_med, df_med_mix)     0.00  0.95
17    (df_low_med, df_high_low)     0.00  0.90
18    (df_low_med, df_high_med)     0.00  0.85
19   (df_low_med, df_high_high)     0.00  0.90
20    (df_low_med, df_high_mix)     0.00  0.90
21    (df_low_high, df_low_mix)     0.00  0.90
22    (df_low_high, df_med_low)     0.17  0.35
23    (df_low_high, df_med_med)     0.00  0.95
24   (df_low_high, df_med_high)     0.00  0.90
25    (df_low_high, df_med_mix)     0.00  0.95
26   (df_low_high, df_high_low)     0.00  0.90
27   (df_low_high, df_high_med)     0.00  0.80
28  (df_low_high, df_high_high)     0.00  0.90
29   (df_low_high, df_high_mix)     0.00  0.85
30     (df_low_mix, df_med_low)     0.00  0.60
31     (df_low_mix, df_med_med)     0.00  0.95
32     (df_low_mix, df_med_mix)     0.00  0.60
33   (df_low_mix, df_high_high)     0.00  0.90
34    (df_low_mix, df_high_mix)     0.01  0.50
35     (df_med_low, df_med_med)     0.00  0.95
36    (df_med_low, df_med_high)     0.00  0.55
37     (df_med_low, df_med_mix)     0.00  0.85
38    (df_med_low, df_high_low)     0.00  0.65
39    (df_med_low, df_high_med)     0.00  0.55
40   (df_med_low, df_high_high)     0.00  0.90
41    (df_med_low, df_high_mix)     0.00  0.70
42    (df_med_med, df_med_high)     0.00  0.95
43     (df_med_med, df_med_mix)     0.00  0.95
44    (df_med_med, df_high_low)     0.00  0.95
45    (df_med_med, df_high_med)     0.00  0.95
46    (df_med_med, df_high_mix)     0.00  0.95
47    (df_med_high, df_med_mix)     0.00  0.70
48   (df_med_high, df_high_low)     0.17  0.35
49   (df_med_high, df_high_med)     0.17  0.35
50  (df_med_high, df_high_high)     0.00  0.90
51   (df_med_high, df_high_mix)     0.00  0.55
52    (df_med_mix, df_high_low)     0.00  0.65
53    (df_med_mix, df_high_med)     0.00  0.55
54   (df_med_mix, df_high_high)     0.00  0.90
55  (df_high_low, df_high_high)     0.00  0.90
56   (df_high_low, df_high_mix)     0.00  0.55
57  (df_high_med, df_high_high)     0.00  0.90
58   (df_high_med, df_high_mix)     0.08  0.40
59  (df_high_high, df_high_mix)     0.00  0.90